<div id="modal_container" class="popup">
        <div class="modal-popup">
            <div class="container">
                <div class="row">
                    <div class="col">
                        <h1 class="tituloPrincipal">Bienvenido a la Expo Mexaba Virtual 2021</h1>
                        <p class="textoCuerpo">
                        Visita los salones Rosa, Azul, Amarillo y Morado, da clic en cada uno de ellos para descubrir a las marcas que hacen posible este evento.
                        </p>
                    </div>
                </div>
            </div>

            <button id="close" class="btn btn-primary botonCerrar">Cerrar</button>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <!-- Image Map Generated by http://www.image-map.net/ -->
                <img src="../img/Secciones/mapa_H.png" usemap="#image-map" class="img-fluid mapa">
                <!--<img src="../img/Secciones/clicks-horizontal-anim.gif" usemap="#image-map" class="img-fluid mapa">-->

                <map name="image-map">
                    <area target="" alt="Salón1" title="Salón1" href="../Mapa/changemap.php?mapaSalon=Salon1" coords="1085,395,1136,439,1130,504,1298,595,1492,502,1490,422,1548,388,1317,248" shape="poly">
                    <area target="" alt="Salón2" title="Salón2" href="../Mapa/changemap.php?mapaSalon=Salon2" coords="1554,390,1495,427,1493,509,1361,604,1507,654,1561,687,1566,766,1790,612,1787,531" shape="poly">
                    <area target="" alt="Salón3" title="Salón3" href="../Mapa/changemap.php?mapaSalon=Salon3" coords="1098,693,1149,660,1202,695,1502,656,1554,688,1556,766,1341,919,1341,834" shape="poly">
                    <area target="" alt="Salón4" title="Salón4" href="../Mapa/changemap.php?mapaSalon=Salon4" coords="859,554,1080,407,1124,439,1129,502,1270,617,1146,654,1091,690" shape="poly">
                    <area target="" alt="Info" title="Info" coords="1761,961,1809,963,1814,1014,1758,1016" shape="poly" id="open">
                </map>
                <!--
                <area target="" alt="Sala1" title="Sala1" href="" coords="1085,395,1136,439,1130,504,1298,595,1492,502,1490,422,1548,388,1317,248" shape="poly">
                <area target="" alt="Sala2" title="Sala2" href="" coords="1554,390,1495,427,1493,509,1361,604,1507,654,1561,687,1566,766,1790,612,1787,531" shape="poly">
                <area target="" alt="Sala3" title="Sala3" href="" coords="1098,693,1149,660,1202,695,1502,656,1554,688,1556,766,1341,919,1341,834" shape="poly">
                <area target="" alt="Sala4" title="Sala4" href="" coords="859,554,1080,407,1124,439,1129,502,1270,617,1146,654,1091,690" shape="poly">
                <area target="" alt="Info" title="Info" href="" coords="1761,961,1809,963,1814,1014,1758,1016" shape="poly">
            -->
            </div>
        </div>
    </div>