<div id="modal_container" class="popup">
        <div class="modal-popup">
            <div class="container">
                <div class="row">
                    <div class="col">
                        <h1 class="tituloPrincipal">Bienvenido a la Expo Mexaba Virtual 2021</h1>
                        <p class="textoCuerpo">
                        Visita los salones Rosa, Azul, Amarillo y Morado, da clic en cada uno de ellos para descubrir a las marcas que hacen posible este evento.
                        </p>
                    </div>
                </div>
            </div>

            <button id="close" class="btn btn-primary botonCerrar">Cerrar</button>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <!-- Image Map Generated by http://www.image-map.net/ -->
                <img src="../img/mapaVertical.png" usemap="#image-map"  class="img-fluid mapa">

                <map name="image-map">
                    <area target="" alt="Salón 1" title="Salón 1" href="" coords="27,1459,214,1501,248,1496,369,1365,368,1286,355,1273,169,1225,28,1385" shape="poly">
                    <area target="" alt="Salón 2" title="Salón 2" href="" coords="32,1195,255,1228,376,1099,364,1044,176,999,34,1159" shape="poly">
                    <area target="" alt="Salón 3" title="Salón 3" href="" coords="202,1000,389,1049,424,1044,542,905,543,867,529,850,343,803,206,967" shape="poly">
                    <area target="" alt="Salón 4" title="Salón 4" href="" coords="640,1003,640,910,726,813,1031,889,1036,973,949,1070,915,1081" shape="poly">
                    <area target="" alt="Info" title="Info" coords="464,1582,626,1620,949,1558,1026,1470,1023,1367,729,1294,601,1318,466,1473" shape="poly" id="open">
                </map>


            </div>
        </div>
    </div>