<div id="modal_container" class="popup">
        <div class="modal-popup">
            <div class="container">
                <div class="row">
                    <div class="col">
                        <h1 class="tituloPrincipal">Bienvenido a la Expo Mexaba Virtual 2021</h1>
                        <p class="textoCuerpo">
                        Visita los salones Rosa, Azul, Amarillo y Morado, da clic en cada uno de ellos para descubrir a las marcas que hacen posible este evento.
                        </p>
                    </div>
                </div>
            </div>

            <button id="close" class="btn btn-primary botonCerrar">Cerrar</button>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <!-- Image Map Generated by http://www.image-map.net/ -->
                <img src="../img/Secciones/seccioneshorizontal.png" usemap="#image-map" class="img-fluid mapa">
                <img src="../img/Secciones/clicks-horizontal-anim.gif" usemap="#image-map" class="img-fluid mapa">

                <map name="image-map">
                    <area target="" alt="Salón1" title="Salón1" href="../Mapa/changemap.php?mapaSalon=Salon1" coords="455,593,459,509,729,433,816,522,823,610,573,685,539,681" shape="poly">
                    <area target="" alt="Salón2" title="Salón2" href="../Mapa/changemap.php?mapaSalon=Salon2" coords="714,406,829,508,1081,438,1077,358,997,265,714,343" shape="poly">
                    <area target="" alt="Salón3" title="Salón3" href="../Mapa/changemap.php?mapaSalon=Salon3" coords="1054,320,1129,417,1167,425,1412,356,1412,270,1331,177,1054,256" shape="poly">
                    <area target="" alt="Salón4" title="Salón4" href="../Mapa/changemap.php?mapaSalon=Salon4" coords="1415,440,1422,352,1598,302,1737,454,1733,534,1565,577" shape="poly">
                    <area target="" alt="Info" title="Info" coords="652,803,654,710,922,636,1047,658,1177,801,1177,903,1031,938,727,887" shape="poly" id="open">
                </map>
            </div>
        </div>
    </div>