<div id="landscape">
   <div>
	<p>
	<img src="../img/giro.png" alt=""><br>
	¡Gira el móvil! <br><span>Please</span>
	</p>
  </div>
</div>
<div id="modal_container" class="popup">
        <div class="modal-popup">
            <div class="container">
                <div class="row">
                    <div class="col">
                        <h1 class="tituloPrincipal">Bienvenido a la Expo Mexaba Virtual 2021</h1>
                        <p class="textoCuerpo">
                        Visita los salones Rosa, Azul, Amarillo y Morado, da clic en cada uno de ellos para descubrir a las marcas que hacen posible este evento.
                        </p>
                    </div>
                </div>
            </div>

            <button id="close" class="btn btn-primary botonCerrar">Cerrar</button>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <!-- Image Map Generated by http://www.image-map.net/ -->
                <img src="../img/Secciones/seccionesvertical.png" usemap="#image-map" class="img-fluid mapa">
                <img src="../img/Secciones/clicks-vertical-anim.gif" usemap="#image-map" class="img-fluid mapa">

                <map name="image-map">
                    <area target="" alt="Salón1" title="Salón1" href="../Mapa/changemap.php?mapaSalon=Salon1" coords="31,1471,33,1387,173,1227,360,1269,373,1290,375,1372,255,1509,220,1523" shape="poly">
                    <area target="" alt="Salón2" title="Salón2" href="../Mapa/changemap.php?mapaSalon=Salon2" coords="256,1236,39,1207,42,1161,180,1004,365,1046,381,1142" shape="poly">
                    <area target="" alt="Salón3" title="Salón3" href="../Mapa/changemap.php?mapaSalon=Salon3" coords="207,1003,392,1047,548,956,545,871,534,853,346,809,209,971" shape="poly">
                    <area target="" alt="Salón4" title="Salón4" href="../Mapa/changemap.php?mapaSalon=Salon4" coords="642,1019,642,913,732,817,1031,889,1031,963,944,1077" shape="poly">
                    <area target="" alt="Info" title="Info" coords="467,1582,468,1472,602,1319,728,1293,1020,1366,1023,1472,954,1554,631,1619" shape="poly" id="open">
                </map>

            </div>
        </div>
    </div>