<div id="landscape">
   <div>
	<p>
	<img src="../img/giro.png" alt=""><br>
	¡Gira el móvil! <br><span>Please</span>
	</p>
  </div>
</div>
<div id="modal_container" class="popup">
        <div class="modal-popup">
            <div class="container">
                <div class="row">
                    <div class="col">
                        <h1 class="tituloPrincipal">Bienvenido a la Expo Mexaba Virtual 2021</h1>
                        <p class="textoCuerpo">
                        Visita los salones Rosa, Azul, Amarillo y Morado, da clic en cada uno de ellos para descubrir a las marcas que hacen posible este evento.
                        </p>
                    </div>
                </div>
            </div>

            <button id="close" class="btn btn-primary botonCerrar">Cerrar</button>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <!-- Image Map Generated by http://www.image-map.net/ -->
                <img src="../img/Secciones/mapa_V.png" usemap="#image-map" class="img-fluid mapa">
                <!--<img src="../img/Secciones/clicks-vertical-anim.gif" usemap="#image-map" class="img-fluid mapa">-->

                <map name="image-map">
                    <area target="" alt="Salón1" title="Salón1" href="../Mapa/changemap.php?mapaSalon=Salon1" coords="337,974,385,1007,379,1078,553,1171,751,1077,747,1004,810,963,570,816" shape="poly">
                    <area target="" alt="Salón2" title="Salón2" href="../Mapa/changemap.php?mapaSalon=Salon2" coords="813,965,753,1005,754,1083,610,1172,764,1230,815,1266,820,1349,1055,1191,1051,1108" shape="poly">
                    <area target="" alt="Salón3" title="Salón3" href="../Mapa/changemap.php?mapaSalon=Salon3" coords="347,1270,398,1238,445,1266,760,1234,812,1264,817,1347,593,1501,591,1417" shape="poly">
                    <area target="" alt="Salón4" title="Salón4" href="../Mapa/changemap.php?mapaSalon=Salon4" coords="107,1127,331,974,383,1009,379,1077,512,1163,398,1238,342,1269" shape="poly">
                    <area target="" alt="Info" title="Info" coords="865,1715,1009,1710,1010,1856,874,1854" shape="poly" id="open">
                </map>
                <!--
                <area target="" alt="Salon1" title="Salon1" href="" coords="337,974,385,1007,379,1078,553,1171,751,1077,747,1004,810,963,570,816" shape="poly">
                <area target="" alt="Salon2" title="Salon2" href="" coords="813,965,753,1005,754,1083,610,1172,764,1230,815,1266,820,1349,1055,1191,1051,1108" shape="poly">
                <area target="" alt="Salon3" title="Salon3" href="" coords="347,1270,398,1238,445,1266,760,1234,812,1264,817,1347,593,1501,591,1417" shape="poly">
                <area target="" alt="Salon4" title="Salon4" href="" coords="107,1127,331,974,383,1009,379,1077,512,1163,398,1238,342,1269" shape="poly">
                <area target="" alt="Info" title="Info" href="" coords="865,1715,1009,1710,1010,1856,874,1854" shape="poly">
                -->
            </div>
        </div>
    </div>